# Generated by Django 5.0.2 on 2024-02-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projet',
            new_name='Project',
        ),
    ]
